# Generated by Django 4.1.3 on 2023-02-09 08:53

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250, verbose_name='Страна')),
                ('title', models.CharField(max_length=250, verbose_name='Название проекта')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Другое',
                'verbose_name_plural': 'Другие',
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250, verbose_name='Страна')),
                ('title', models.CharField(max_length=250, verbose_name='Название проекта')),
                ('title_contracts', models.CharField(max_length=250, verbose_name='Название контракта')),
                ('finance', models.CharField(max_length=250, verbose_name='Финансирование')),
                ('pricath', models.CharField(max_length=250, verbose_name='Номер приказа')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('date', models.DateTimeField(verbose_name='Срок подачи заявок')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тендер',
                'verbose_name_plural': 'Тендера',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250, verbose_name='Страна')),
                ('title', models.CharField(max_length=250, verbose_name='Название проекта')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('date', models.DateTimeField(verbose_name='Срок подачи заявок')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Ваканция',
                'verbose_name_plural': 'Ваканции',
            },
        ),
    ]
