# Generated by Django 4.1.3 on 2023-02-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='finance',
        ),
    ]
