# Generated by Django 4.1.3 on 2023-02-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0002_remove_tender_country_remove_tender_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='filr',
            field=models.FileField(blank=True, upload_to='files', verbose_name='Добавить файл'),
        ),
    ]
