# Generated by Django 4.1.3 on 2023-02-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0003_tender_filr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tender',
            old_name='filr',
            new_name='file',
        ),
    ]
