# Generated by Django 4.1.3 on 2023-02-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0004_rename_filr_tender_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='file',
            field=models.FileField(blank=True, upload_to='files', verbose_name='Добавить файл'),
        ),
    ]
