# Generated by Django 4.1.3 on 2023-02-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0006_other_created_other_is_active_tender_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='file',
            field=models.FileField(null=True, upload_to='files', verbose_name='Добавить файл'),
        ),
    ]
