# Generated by Django 4.1.3 on 2023-01-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('city', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('title', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('text', models.TextField(verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='file')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Онлайн заявка',
                'verbose_name_plural': 'Онлайн заявки',
            },
        ),
    ]
