# Generated by Django 4.1.3 on 2023-02-07 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_alter_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create',
            name='date',
        ),
        migrations.AddField(
            model_name='create',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создание'),
            preserve_default=False,
        ),
    ]
