# Generated by Django 4.1.3 on 2023-07-12 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_remove_create_date_create_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_name', models.CharField(max_length=50, verbose_name='Организационно-правовая форма')),
            ],
            options={
                'verbose_name': 'форма',
                'verbose_name_plural': 'формы',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=250, verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Область',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=250, verbose_name='Сектор')),
            ],
            options={
                'verbose_name': 'Сектор',
                'verbose_name_plural': 'Сектора',
            },
        ),
        migrations.RemoveField(
            model_name='create',
            name='text',
        ),
        migrations.RemoveField(
            model_name='create',
            name='title',
        ),
        migrations.AddField(
            model_name='create',
            name='adress',
            field=models.CharField(default=1, max_length=200, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='business_plan',
            field=models.CharField(default=1, max_length=255, verbose_name='Бизнес план'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='certificate',
            field=models.CharField(default=1, max_length=255, verbose_name='Свидетельство о госрегистрации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='credit_term',
            field=models.CharField(default='', max_length=255, verbose_name='Срок кредита'),
        ),
        migrations.AddField(
            model_name='create',
            name='desired_schedule',
            field=models.CharField(default=1, max_length=255, verbose_name='Желаемый график погашения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='doc_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Наименование документа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='entitlement',
            field=models.CharField(default=1, max_length=255, verbose_name='Правоустанавливающий'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='file_before',
            field=models.FileField(blank=True, null=True, upload_to='file'),
        ),
        migrations.AddField(
            model_name='create',
            name='file_rear',
            field=models.FileField(blank=True, null=True, upload_to='file'),
        ),
        migrations.AddField(
            model_name='create',
            name='financial_statements',
            field=models.CharField(default=1, max_length=255, verbose_name='Финансовая отчетность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='founding_document',
            field=models.CharField(default=1, max_length=255, verbose_name='Учредительный документ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='indicative',
            field=models.CharField(default=1, max_length=255, verbose_name='Ориентировочная оценочная стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='inn',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=255, unique=True, verbose_name='ИНН'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Согласие'),
        ),
        migrations.AddField(
            model_name='create',
            name='is_actives',
            field=models.BooleanField(default=True, verbose_name='Ознакомлен '),
        ),
        migrations.AddField(
            model_name='create',
            name='job_title',
            field=models.CharField(default=1, max_length=50, verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='location',
            field=models.CharField(default=1, max_length=255, verbose_name='Месторасположение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='middle_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='organ_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Наименование хозяйствующего субъекта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='own_contribution',
            field=models.CharField(default=1, max_length=255, verbose_name='обственный вклад в денежном выражении'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='owner',
            field=models.CharField(default=1, max_length=255, verbose_name='Собственник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='requested_amount',
            field=models.CharField(default=1, max_length=255, verbose_name='Запрашиваемая сумма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='supervisor_first_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='supervisor_job_title',
            field=models.CharField(default=1, max_length=50, verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='supervisor_last_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='supervisor_middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='create',
            name='supervisor_phone',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=255, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='target_direction',
            field=models.CharField(default=1, max_length=255, verbose_name='Целевое направление кредита'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='create',
            name='city',
            field=models.CharField(max_length=200, verbose_name='Город/Село'),
        ),
        migrations.AlterField(
            model_name='create',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='create',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=255, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='create',
            name='organizations',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online.organizations'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online.region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online.sector'),
            preserve_default=False,
        ),
    ]
