# Generated by Django 4.1.3 on 2023-07-13 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_organizations_region_sector_remove_create_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='organizations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.organizations', verbose_name='Организационно-правовая форма'),
        ),
        migrations.AlterField(
            model_name='create',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.region', verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='create',
            name='requested_amount',
            field=models.IntegerField(max_length=255, verbose_name='Запрашиваемая сумма'),
        ),
        migrations.AlterField(
            model_name='create',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.sector', verbose_name='Отрасль/Сектор'),
        ),
    ]
