# Generated by Django 4.1.3 on 2023-02-02 05:42

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_add', models.ImageField(blank=True, upload_to='img', verbose_name='Фото')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Страна')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Статья')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Добавить',
                'verbose_name_plural': 'Добавить фотографию',
            },
        ),
    ]
