# Generated by Django 4.1.3 on 2023-02-06 12:11

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('cover', '200x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(blank=True, upload_to='img', verbose_name='Добавить фото'),
        ),
    ]
