# Generated by Django 4.1.3 on 2023-02-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_articles_cropping_alter_articles_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='cropping',
        ),
    ]
