# Generated by Django 4.1.3 on 2023-02-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_articles_cropping'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='file',
            field=models.FileField(blank=True, upload_to='files', verbose_name='Добавить файл'),
        ),
    ]
