# Generated by Django 4.1.3 on 2023-02-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_articles_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='file',
        ),
    ]
