# Generated by Django 4.1.3 on 2023-02-14 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_articles_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
