# Generated by Django 4.1.3 on 2023-05-04 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_articles_created_articles_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-created'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
