# Generated by Django 4.1.3 on 2023-02-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10, verbose_name='Название')),
                ('img1', models.ImageField(blank=True, upload_to='img')),
                ('title1', models.CharField(blank=True, max_length=250, verbose_name='Название 1 каруселя')),
                ('text1', models.CharField(blank=True, max_length=250, verbose_name='Текст 1 каруселя')),
                ('img2', models.ImageField(blank=True, upload_to='img')),
                ('title2', models.CharField(blank=True, max_length=250, verbose_name='Название 2 каруселя')),
                ('text2', models.CharField(blank=True, max_length=250, verbose_name='Текст 2 каруселя')),
                ('img3', models.ImageField(blank=True, upload_to='img')),
                ('title3', models.CharField(blank=True, max_length=250, verbose_name='Название 3 каруселя')),
                ('text3', models.CharField(blank=True, max_length=250, verbose_name='Текст 3 каруселя')),
                ('img4', models.ImageField(blank=True, upload_to='img')),
                ('title4', models.CharField(blank=True, max_length=250, verbose_name='Название 4 каруселя')),
                ('text4', models.CharField(blank=True, max_length=250, verbose_name='Текст 4 каруселя')),
                ('img5', models.ImageField(blank=True, upload_to='img')),
                ('title5', models.CharField(blank=True, max_length=250, verbose_name='Название 5 каруселя')),
                ('text5', models.CharField(blank=True, max_length=250, verbose_name='Текст 5 каруселя')),
                ('img6', models.ImageField(blank=True, upload_to='img')),
                ('title6', models.CharField(blank=True, max_length=250, verbose_name='Название 6 каруселя')),
                ('text6', models.CharField(blank=True, max_length=250, verbose_name='Текст 6 каруселя')),
                ('img7', models.ImageField(blank=True, upload_to='img')),
                ('title7', models.CharField(blank=True, max_length=250, verbose_name='Название 7 каруселя')),
                ('text7', models.CharField(blank=True, max_length=250, verbose_name='Текст 7 каруселя')),
                ('img8', models.ImageField(blank=True, upload_to='img')),
                ('title8', models.CharField(blank=True, max_length=250, verbose_name='Название 8 каруселя')),
                ('text8', models.CharField(blank=True, max_length=250, verbose_name='Текст 8 каруселя')),
                ('img9', models.ImageField(blank=True, upload_to='img')),
                ('title9', models.CharField(blank=True, max_length=250, verbose_name='Название 9 каруселя')),
                ('text9', models.CharField(blank=True, max_length=250, verbose_name='Текст 9 каруселя')),
                ('img10', models.ImageField(blank=True, upload_to='img')),
                ('title10', models.CharField(blank=True, max_length=250, verbose_name='Название 10 каруселя')),
                ('text10', models.CharField(blank=True, max_length=250, verbose_name='Текст 10 каруселя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Добавить фото',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Ф.И.О')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Почта')),
                ('kab', models.CharField(blank=True, max_length=255, verbose_name='Кабинет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
            ],
            options={
                'verbose_name': 'Списиок сотрудников',
                'verbose_name_plural': 'Таблица сотрудников',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Добавить видео',
            },
        ),
    ]
