# Generated by Django 4.1.3 on 2023-05-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_photo_img10_remove_photo_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=55, verbose_name='Название Каруселя'),
        ),
    ]
