# Generated by Django 4.1.3 on 2023-05-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_photo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo', verbose_name='Добавить фото'),
        ),
    ]
