# Generated by Django 4.1.3 on 2023-05-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_staff_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
