# Generated by Django 4.1.3 on 2023-07-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
